sudo: required

# language: node_js
# node_js:
#   - 10.16.0

# dist: trusty

# addons:
#   chrome: stable

# services:
#   - docker

# before_install:
#   - docker build -t dockerimage -f dockerfile.dev .

# script:
#   - docker run dockerimage ng test --watch=false --browsers=ChromeHeadless


language: node_js
node_js:
  - "10.16.0"
sudo: true

addons:
  chrome: stable

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng test --watch=false --browsers=ChromeHeadless

deploy:
  provider: elasticbeanstalk
  access_key_id:
   secure: "$accesskey"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: "us-east-2"
  env: "portfolio-env"
  bucket_name: "elasticbeanstalk-us-east-2-646900675324"
  bucket_path: "portfolio"
