# sudo: required

# language: node_js
# node_js:
#   - 10.16.0

# dist: trusty

# addons:
#   chrome: stable

# services:
#   - docker

# before_install:
#   - docker build -t dockerimage -f dockerfile.dev .

# script:
#   - docker run dockerimage npm run test-headless

language: node_js
node_js:
  - "10.16.0"
sudo: true

addons:
  chrome: stable

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng test --watch=false --browsers=ChromeHeadless
