# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: UseNode@1
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      echo variables['Build.SourceBranch']
      echo ${variables['Build.SourceBranch']}
      yarn install
    displayName: "Yarn install"
    condition: succeeded()

  - script: |
      yarn global add @angular/cli
    displayName: "Install Angular"
    condition: succeeded()

  - script: |
      yarn test-headless
    timeoutInMinutes: 1
    displayName: "Unit Testing"

  - script: |
      yarn build
    displayName: "Build App"
